version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_PASSWORD: '0hello1'
      MYSQL_ROOT_PASSWORD: '0hello1'
    ports:
      - '3305:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
